name: Haskell CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up GHC with ghcup
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.7'
        cabal-version: '3.10.1.0'

    - name: Update package list and install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgmp-dev

    - name: Cabal update
      run: cabal update

    - name: Run tests
      run: cabal test all
